org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.builder.sdkDownload=true

android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.aapt2FromMavenOverride=/nix/store/wgvkh0mrmba3dpign2hqv3xf64cs9psb-android-sdk-build-tools-34.0.0/libexec/android-sdk/build-tools/34.0.0/aapt2
