org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.builder.sdkDownload=false

android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.aapt2FromMavenOverride=/nix/store/8s2iw397zmnh22gs4z8b306lvsylkqh8-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
