org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.builder.sdkDownload=true

android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.aapt2FromMavenOverride=/nix/store/hg4l32100v9akzcwbqcnijnsczc0jq8z-android-sdk-build-tools-35.0.0/libexec/android-sdk/build-tools/35.0.0/aapt2
