plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sinanjam.arsiv'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'com.sinanjam.arsiv'
        minSdk 23
        targetSdk 35
        versionCode 24
        versionName '2.1-install-fix'
    }

    signingConfigs {
        stableDebug {
            storeFile file('../keystore/balkes-arsivi-stable.jks')
            storePassword 'balkesarsivi'
            keyAlias 'balkesarsivi'
            keyPassword 'balkesarsivi'
            enableV1Signing true
            enableV2Signing true
            enableV3Signing true
            enableV4Signing false
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableDebug
            debuggable false
            applicationIdSuffix ''
            versionNameSuffix ''
        }
        release {
            signingConfig signingConfigs.stableDebug
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}


dependencies {
    implementation 'androidx.core:core:1.13.1'
}
